apiVersion: networking.k8s.io/v1 Ingress
kind: Ingress
metadata:
  name: app-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: myapp.com
    http:
      paths:
      - path: /client
        backend:
          serviceName: client
          servicePort: 3000
      - path: /server
        backend:
          serviceName: server
          servicePort: 7000

